alias artisan='php artisan'
alias phpunit='vendor/bin/phpunit'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias svndiff='svn diff "$*" | colordiff'
alias codecept='vendor/bin/codecept'
alias phpspec='vendor/bin/phpspec'
alias behat='vendor/bin/behat'
alias git-diff-lines='GIT_EXTERNAL_DIFF=~/bin/diff_ln.sh git diff'
alias phinx='vendor/bin/phinx'
alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'
alias fixssh='eval $(tmux showenv -s SSH_AUTH_SOCK)'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
